// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PluginRuntime.Infrastructure.Persistence;

#nullable disable

namespace PluginRuntime.Infrastructure.Migrations
{
    [DbContext(typeof(PluginRuntimeDbContext))]
    partial class PluginRuntimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // plugins
            modelBuilder.Entity("PluginRuntime.Core.Entities.Plugin", b =>
            {
                b.Property<Guid>("PluginId").HasColumnName("plugin_id").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnName("name").HasColumnType("character varying(200)");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(500).HasColumnName("display_name").HasColumnType("character varying(500)");
                b.Property<string>("Description").HasColumnName("description").HasColumnType("text");
                b.Property<Guid>("OwnerId").HasColumnName("owner_id").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnName("status").HasColumnType("character varying(50)");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("DeletedAt").HasColumnName("deleted_at").HasColumnType("timestamp with time zone");
                b.HasKey("PluginId");
                b.HasAlternateKey("Name");
                b.HasIndex("Name").HasDatabaseName("idx_plugins_name");
                b.HasIndex("Status").HasFilter("deleted_at IS NULL").HasDatabaseName("idx_plugins_status");
                b.ToTable("plugins");
            });

            // plugin_versions
            modelBuilder.Entity("PluginRuntime.Core.Entities.PluginVersion", b =>
            {
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<Guid>("PluginId").HasColumnName("plugin_id").HasColumnType("uuid");
                b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnName("version").HasColumnType("character varying(50)");
                b.Property<string>("StorageUri").IsRequired().HasMaxLength(2000).HasColumnName("storage_uri").HasColumnType("character varying(2000)");
                b.Property<string>("Sha256").IsRequired().HasMaxLength(64).HasColumnName("sha256").HasColumnType("character varying(64)");
                b.Property<string>("EntryPoint").IsRequired().HasMaxLength(500).HasColumnName("entry_point").HasColumnType("character varying(500)");
                b.Property<string>("EntryClass").IsRequired().HasMaxLength(500).HasColumnName("entry_class").HasColumnType("character varying(500)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnName("status").HasColumnType("character varying(50)");
                b.Property<Guid?>("ApprovedBy").HasColumnName("approved_by").HasColumnType("uuid");
                b.Property<DateTime?>("ApprovedAt").HasColumnName("approved_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("VersionId");
                b.HasIndex(new[] { "PluginId", "Version" }).IsUnique().HasDatabaseName("uq_plugin_version");
                b.HasIndex("PluginId").HasDatabaseName("idx_versions_plugin_id");
                b.HasIndex("Status").HasDatabaseName("idx_versions_status");
                b.ToTable("plugin_versions");
            });

            // manifests
            modelBuilder.Entity("PluginRuntime.Core.Entities.Manifest", b =>
            {
                b.Property<Guid>("ManifestId").HasColumnName("manifest_id").HasColumnType("uuid");
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<string>("ManifestVersion").IsRequired().HasMaxLength(20).HasColumnName("manifest_version").HasColumnType("character varying(20)");
                b.Property<string>("TargetCoreVersion").IsRequired().HasMaxLength(100).HasColumnName("target_core_version").HasColumnType("character varying(100)");
                b.Property<JsonElement>("Permissions").IsRequired().HasColumnName("permissions").HasColumnType("jsonb");
                b.Property<JsonElement>("Capabilities").IsRequired().HasColumnName("capabilities").HasColumnType("jsonb");
                b.Property<int>("ExecutionTimeoutMs").HasColumnName("execution_timeout_ms").HasColumnType("integer");
                b.Property<int>("MaxMemoryMb").HasColumnName("max_memory_mb").HasColumnType("integer");
                b.Property<int>("MaxCpuMs").HasColumnName("max_cpu_ms").HasColumnType("integer");
                b.Property<bool>("AllowParallel").HasColumnName("allow_parallel").HasColumnType("boolean");
                b.Property<string>("Signature").IsRequired().HasColumnName("signature").HasColumnType("text");
                b.Property<string>("SignatureAlgorithm").IsRequired().HasMaxLength(50).HasColumnName("signature_algorithm").HasColumnType("character varying(50)");
                b.Property<string>("PublicKeyId").IsRequired().HasMaxLength(200).HasColumnName("public_key_id").HasColumnType("character varying(200)");
                b.Property<DateTime>("IssuedAt").HasColumnName("issued_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("ExpiresAt").HasColumnName("expires_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("ManifestId");
                b.HasAlternateKey("VersionId");
                b.HasIndex("VersionId").HasDatabaseName("idx_manifests_version_id");
                b.HasIndex("ExpiresAt").HasDatabaseName("idx_manifests_expires_at");
                b.ToTable("manifests");
            });

            // executions
            modelBuilder.Entity("PluginRuntime.Core.Entities.Execution", b =>
            {
                b.Property<Guid>("ExecutionId").HasColumnName("execution_id").HasColumnType("uuid");
                b.Property<Guid>("PluginId").HasColumnName("plugin_id").HasColumnType("uuid");
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<string>("TraceId").IsRequired().HasMaxLength(200).HasColumnName("trace_id").HasColumnType("character varying(200)");
                b.Property<string>("CorrelationId").HasMaxLength(200).HasColumnName("correlation_id").HasColumnType("character varying(200)");
                b.Property<string>("TenantId").HasMaxLength(200).HasColumnName("tenant_id").HasColumnType("character varying(200)");
                b.Property<string>("UserId").HasMaxLength(200).HasColumnName("user_id").HasColumnType("character varying(200)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnName("status").HasColumnType("character varying(50)");
                b.Property<string>("ErrorCode").HasMaxLength(50).HasColumnName("error_code").HasColumnType("character varying(50)");
                b.Property<string>("ErrorMessage").HasColumnName("error_message").HasColumnType("text");
                b.Property<DateTime>("StartTime").HasColumnName("start_time").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("EndTime").HasColumnName("end_time").HasColumnType("timestamp with time zone");
                b.Property<int?>("DurationMs").HasColumnName("duration_ms").HasColumnType("integer");
                b.Property<string>("NodeId").HasMaxLength(200).HasColumnName("node_id").HasColumnType("character varying(200)");
                b.HasKey("ExecutionId");
                b.HasIndex("TraceId").HasDatabaseName("idx_executions_trace_id");
                b.HasIndex(new[] { "PluginId", "VersionId" }).HasDatabaseName("idx_executions_plugin_version");
                b.HasIndex("StartTime").IsDescending(true).HasDatabaseName("idx_executions_start_time");
                b.HasIndex("Status").HasFilter("status = 'Running'").HasDatabaseName("idx_executions_status");
                b.ToTable("executions");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
            {
                b.Property<Guid>("AuditId").HasColumnName("audit_id").HasColumnType("uuid");
                b.Property<DateTime>("Timestamp").HasColumnName("timestamp").HasColumnType("timestamp with time zone");
                b.Property<string>("ActorId").IsRequired().HasMaxLength(200).HasColumnName("actor_id").HasColumnType("character varying(200)");
                b.Property<string>("ActorType").IsRequired().HasMaxLength(50).HasColumnName("actor_type").HasColumnType("character varying(50)");
                b.Property<string>("Action").IsRequired().HasMaxLength(200).HasColumnName("action").HasColumnType("character varying(200)");
                b.Property<string>("ResourceType").IsRequired().HasMaxLength(100).HasColumnName("resource_type").HasColumnType("character varying(100)");
                b.Property<string>("ResourceId").IsRequired().HasMaxLength(200).HasColumnName("resource_id").HasColumnType("character varying(200)");
                b.Property<string>("IpAddress").HasMaxLength(50).HasColumnName("ip_address").HasColumnType("character varying(50)");
                b.Property<string>("Result").IsRequired().HasMaxLength(50).HasColumnName("result").HasColumnType("character varying(50)");
                b.Property<string>("Metadata").HasColumnName("metadata").HasColumnType("jsonb");
                b.HasKey("AuditId");
                b.HasIndex("Timestamp").IsDescending(true).HasDatabaseName("idx_audit_timestamp");
                b.HasIndex("Action").HasDatabaseName("idx_audit_action");
                b.HasIndex(new[] { "ResourceType", "ResourceId" }).HasDatabaseName("idx_audit_resource");
                b.ToTable("audit_logs");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.CapabilityEntity", b =>
            {
                b.Property<Guid>("CapabilityId").HasColumnName("capability_id").HasColumnType("uuid");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnName("name").HasColumnType("character varying(200)");
                b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnName("version").HasColumnType("character varying(50)");
                b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnName("category").HasColumnType("character varying(100)");
                b.Property<string>("Description").HasColumnName("description").HasColumnType("text");
                b.Property<bool>("Enabled").HasColumnName("enabled").HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("CapabilityId");
                b.HasAlternateKey("Name");
                b.ToTable("capabilities");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.RevocationEntity", b =>
            {
                b.Property<Guid>("RevocationId").HasColumnName("revocation_id").HasColumnType("uuid");
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<string>("Reason").IsRequired().HasColumnName("reason").HasColumnType("text");
                b.Property<Guid>("RevokedBy").HasColumnName("revoked_by").HasColumnType("uuid");
                b.Property<DateTime>("RevokedAt").HasColumnName("revoked_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("ExpiresAt").HasColumnName("expires_at").HasColumnType("timestamp with time zone");
                b.HasKey("RevocationId");
                b.HasIndex("VersionId").HasDatabaseName("idx_revocations_version");
                b.ToTable("revocations");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.ApprovalEntity", b =>
            {
                b.Property<Guid>("ApprovalId").HasColumnName("approval_id").HasColumnType("uuid");
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<Guid>("ReviewerId").HasColumnName("reviewer_id").HasColumnType("uuid");
                b.Property<string>("Decision").IsRequired().HasMaxLength(50).HasColumnName("decision").HasColumnType("character varying(50)");
                b.Property<string>("Comment").HasColumnName("comment").HasColumnType("text");
                b.Property<DateTime>("DecidedAt").HasColumnName("decided_at").HasColumnType("timestamp with time zone");
                b.HasKey("ApprovalId");
                b.ToTable("approvals");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.RuntimeNodeEntity", b =>
            {
                b.Property<string>("NodeId").IsRequired().HasMaxLength(200).HasColumnName("node_id").HasColumnType("character varying(200)");
                b.Property<string>("Hostname").IsRequired().HasMaxLength(500).HasColumnName("hostname").HasColumnType("character varying(500)");
                b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnName("version").HasColumnType("character varying(50)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnName("status").HasColumnType("character varying(50)");
                b.Property<DateTime>("StartedAt").HasColumnName("started_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("LastHeartbeat").HasColumnName("last_heartbeat").HasColumnType("timestamp with time zone");
                b.HasKey("NodeId");
                b.ToTable("runtime_nodes");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.ExtensionRegistryEntity", b =>
            {
                b.Property<string>("ExtensionId").IsRequired().HasMaxLength(200).HasColumnName("extension_id").HasColumnType("character varying(200)");
                b.Property<Guid>("PluginId").HasColumnName("plugin_id").HasColumnType("uuid");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(500).HasColumnName("display_name").HasColumnType("character varying(500)");
                b.Property<string>("Description").HasColumnName("description").HasColumnType("text");
                b.Property<Guid>("AuthorId").HasColumnName("author_id").HasColumnType("uuid");
                b.Property<string>("Visibility").IsRequired().HasMaxLength(50).HasColumnName("visibility").HasColumnType("character varying(50)");
                b.Property<string>("Category").HasMaxLength(100).HasColumnName("category").HasColumnType("character varying(100)");
                b.Property<string>("LatestVersion").HasMaxLength(50).HasColumnName("latest_version").HasColumnType("character varying(50)");
                b.Property<int>("TotalVersions").HasColumnName("total_versions").HasColumnType("integer");
                b.Property<int>("SubscriberCount").HasColumnName("subscriber_count").HasColumnType("integer");
                b.Property<string>("InvocationPolicy").HasColumnName("invocation_policy").HasColumnType("jsonb");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
                b.HasKey("ExtensionId");
                b.HasIndex("Visibility").HasDatabaseName("idx_registry_visibility");
                b.HasIndex("AuthorId").HasDatabaseName("idx_registry_author");
                b.HasIndex("Category").HasDatabaseName("idx_registry_category");
                b.ToTable("extension_registry");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.ExtensionSubscriptionEntity", b =>
            {
                b.Property<Guid>("SubscriptionId").HasColumnName("subscription_id").HasColumnType("uuid");
                b.Property<string>("SourceExtensionId").IsRequired().HasMaxLength(200).HasColumnName("source_extension_id").HasColumnType("character varying(200)");
                b.Property<string>("TargetExtensionId").IsRequired().HasMaxLength(200).HasColumnName("target_extension_id").HasColumnType("character varying(200)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnName("status").HasColumnType("character varying(50)");
                b.Property<string>("Reason").HasColumnName("reason").HasColumnType("text");
                b.Property<string>("ExpectedUsage").HasColumnName("expected_usage").HasColumnType("jsonb");
                b.Property<string>("Conditions").HasColumnName("conditions").HasColumnType("text");
                b.Property<Guid?>("DecidedBy").HasColumnName("decided_by").HasColumnType("uuid");
                b.Property<DateTime?>("DecidedAt").HasColumnName("decided_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("ExpiresAt").HasColumnName("expires_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime?>("RevokedAt").HasColumnName("revoked_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("SubscriptionId");
                b.HasIndex(new[] { "SourceExtensionId", "TargetExtensionId" }).IsUnique().HasDatabaseName("uq_subscription");
                b.HasIndex("SourceExtensionId").HasDatabaseName("idx_subscriptions_source");
                b.HasIndex("TargetExtensionId").HasDatabaseName("idx_subscriptions_target");
                b.HasIndex("Status").HasDatabaseName("idx_subscriptions_status");
                b.ToTable("extension_subscriptions");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.PermissionReviewEntity", b =>
            {
                b.Property<Guid>("ReviewId").HasColumnName("review_id").HasColumnType("uuid");
                b.Property<Guid>("VersionId").HasColumnName("version_id").HasColumnType("uuid");
                b.Property<string>("Permissions").IsRequired().HasColumnName("permissions").HasColumnType("jsonb");
                b.Property<string>("RiskSummary").IsRequired().HasColumnName("risk_summary").HasColumnType("jsonb");
                b.Property<string>("PermissionDiff").HasColumnName("permission_diff").HasColumnType("jsonb");
                b.Property<string>("OverallRiskLevel").IsRequired().HasMaxLength(50).HasColumnName("overall_risk_level").HasColumnType("character varying(50)");
                b.Property<Guid?>("ReviewerId").HasColumnName("reviewer_id").HasColumnType("uuid");
                b.Property<string>("Decision").HasMaxLength(50).HasColumnName("decision").HasColumnType("character varying(50)");
                b.Property<string>("Comment").HasColumnName("comment").HasColumnType("text");
                b.Property<string>("Conditions").HasColumnName("conditions").HasColumnType("jsonb");
                b.Property<DateTime?>("DecidedAt").HasColumnName("decided_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("ReviewId");
                b.ToTable("permission_reviews");
            });

            modelBuilder.Entity("PluginRuntime.Infrastructure.Persistence.Entities.DeclarativeConfigEntity", b =>
            {
                b.Property<Guid>("ConfigId").HasColumnName("config_id").HasColumnType("uuid");
                b.Property<string>("ExtensionId").IsRequired().HasMaxLength(200).HasColumnName("extension_id").HasColumnType("character varying(200)");
                b.Property<string>("Version").IsRequired().HasMaxLength(50).HasColumnName("version").HasColumnType("character varying(50)");
                b.Property<string>("Config").IsRequired().HasColumnName("config").HasColumnType("jsonb");
                b.Property<string>("InputSchema").HasColumnName("input_schema").HasColumnType("jsonb");
                b.Property<string>("OutputSchema").HasColumnName("output_schema").HasColumnType("jsonb");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.HasKey("ConfigId");
                b.HasIndex(new[] { "ExtensionId", "Version" }).IsUnique().HasDatabaseName("uq_declarative_version");
                b.ToTable("declarative_configs");
            });
#pragma warning restore 612, 618
        }
    }
}
